markdown: redcarpet
highlighter: pygments
sass:
  sass_dir: site_assets/_sass
  style: :compressed

title: DaycareIQ.com Blog
description: 'Updates, education and product information about Daycares!'
paginate: 5
main_app_url: https://www.daycareiq.com/
production_url: https://blog.daycareiq.com
baseurl: ''
permalink: /:categories/:year-:title
logo: "/site_assets/images/logo.png"
cover: "/site_assets/images/group_of_babies.jpg"

email: info@daycareIQ.com
name: 'DaycareIQ.com'
twitter: daycareiq
google_analytics_id: UA-58909290-2

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      sitemap: true
      author: "dciq"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

social:
  - icon: twitter
    url: https://twitter.com/daycareiq
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  # - icon:	github
  #   url:	https://github.com/brandonparsons
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

  #  - icon:	facebook
  #    url:	https://facebook.com/???
  #    desc: Connect with me facebook
  #    share_url: //www.facebook.com/sharer.php
  #    share_title: ?t=
  #    share_link: "&amp;u="

  #  - icon:	google-plus
  #    url:	https://google.com/???
  #    desc:	Add me on google+
  #    share_url:
  #    share_title:
  #    share_link:

prose:
  siteurl: 'http://blog.daycareiq.com'
  relativeLinks: 'http://blog.daycareiq.com/links.jsonp'
  # rooturl: '_posts' # uncomment to limit editing to the _posts directory
  media: 'site_assets/article_images'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          placeholder: 'Title, if not directly correct from filename'
      - name: "description"
        field:
          element: "text"
          placeholder: 'Meta description, for SEO. Limit to ~170 characters.'
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "featured"
              value: "featured"
            - name: "updates"
              value: "updates"
            - name: "alberta"
              value: "alberta"
            - name: "daycares"
              value: "daycares"
            - name: "regulation"
              value: "regulation"
            - name: "accreditation"
              value: "accreditation"
            - name: "subsidy"
              value: "subsidy"
            - name: "child care"
              value: "child care"

exclude:
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - README.md
  - THEME-LICENSE
